name: Trigger on Hotfix Label

on:
  pull_request:
    types: [closed]

jobs:
  trigger-hotfix:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check for hotfix label
        id: check_label
        run: |
          echo "Checking PR labels..."
          HOTFIX_LABEL_REGEX="^v[0-9]+\.[0-9]+\.[0-9]+-hotfix\.[0-9]+$"
          MATCHED=false
          MATCHED_VERSION=

          labels=$(echo '${{ toJson(github.event.pull_request.labels) }}' | jq -r '.[].name')
          echo "Labels: $labels"

          for name in $labels; do
            echo "Label name: $name"
            if [[ "$name" =~ $HOTFIX_LABEL_REGEX ]]; then
              MATCHED=true
              MATCHED_VERSION=$name
              break
            fi
          done

          echo "matched=$MATCHED" >> $GITHUB_OUTPUT
          echo "matched_version=$MATCHED_VERSION" >> $GITHUB_OUTPUT
      - name: Run your hotfix workflow
        if: steps.check_label.outputs.matched == 'true'
        run: |
          echo "🔥 Hotfix label matched! Run your tasks here..."
          echo "matched_version=${{ steps.check_label.outputs.matched_version }}" >> $GITHUB_OUTPUT
