name: Trigger on Hotfix Label

on:
  pull_request:
    types: [closed]

jobs:
  trigger-hotfix:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for hotfix label
        id: check_label
        run: |
          echo "Checking PR labels..."
          HOTFIX_LABEL_REGEX="^v[0-9]+\.[0-9]+\.[0-9]+-hotfix\.[0-9]+$"
          MATCHED=false
          MATCHED_VERSION=
          CLEAN_VERSION=
          CLEAN_GENERIC_VERSION=

          labels=$(echo '${{ toJson(github.event.pull_request.labels) }}' | jq -r '.[].name')
          echo "Labels: $labels"

          for name in $labels; do
            echo "Label name: $name"
            if [[ "$name" =~ $HOTFIX_LABEL_REGEX ]]; then
              MATCHED=true
              MATCHED_VERSION=$name
              clean_version=$(echo "$name" | sed -E 's/^v([0-9]+\.[0-9]+\.[0-9]+)-hotfix\.[0-9]+$/\1/')
              clean_generic_version=$(echo "$clean_version" | sed -E 's/([0-9]+\.[0-9]+)\.[0-9]+/\1.x/')

              echo "CLEAN VERSION: $clean_version"
              echo "CLEAN GENERIC VERSION: $clean_generic_version"
              
              CLEAN_VERSION=$clean_version
              CLEAN_GENERIC_VERSION=$clean_generic_version
              break
            fi
          done

          echo "matched=$MATCHED" >> $GITHUB_OUTPUT
          echo "matched_version=$MATCHED_VERSION" >> $GITHUB_OUTPUT
          echo "clean_version=$CLEAN_VERSION" >> $GITHUB_OUTPUT
          echo "clean_generic_version=$CLEAN_GENERIC_VERSION" >> $GITHUB_OUTPUT

      - name: Check if corresponding release branch exists
        id: check_release_branch
        if: steps.check_label.outputs.matched == 'true'
        run: |
          echo "GENERIC VERSION: ${{ steps.check_label.outputs.clean_generic_version }}"
          echo "VERSION: ${{ steps.check_label.outputs.clean_version }}"
          echo "LABEL NAME: ${{ steps.check_label.outputs.matched_version }}"
          echo "matched: ${{ steps.check_label.outputs.matched }}"

          SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"

          CLEAN_GENERIC_VERSION=${{ steps.check_label.outputs.clean_generic_version }}
          BRANCH_NAME="release/$CLEAN_GENERIC_VERSION"
          echo "Checking if branch $BRANCH_NAME exists..."
          git fetch origin $BRANCH_NAME || true

          if git rev-parse --verify --quiet origin/$BRANCH_NAME; then
            echo "branch_exists=true" >> $GITHUB_OUTPUT
            echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
            echo "source_branch=$SOURCE_BRANCH" >> $GITHUB_OUTPUT
            echo "Branch $BRANCH_NAME exists"
          else
            echo "Branch $BRANCH_NAME does not exist"
            echo "branch_exists=false" >> $GITHUB_OUTPUT

            exit 1
          fi

      - name: Fetch and checkout release branch
        if: steps.check_label.outputs.matched == 'true'
        run: |
          RELEASE_BRANCH="${{ steps.check_label.outputs.branch_name }}"

          echo "Fetching release branch $RELEASE_BRANCH..."

          git fetch origin "$RELEASE_BRANCH"
          git checkout "$RELEASE_BRANCH"

      - name: Cherry-pick commits from ${{ steps.check_label.outputs.source_branch }} into ${{ steps.check_label.outputs.branch_name }}
        if: steps.check_label.outputs.matched == 'true' && steps.check_label.outputs.branch_exists == 'true'
        run: |
          SOURCE_BRANCH="${{ steps.check_label.outputs.source_branch }}"
          BRANCH_NAME="${{ steps.check_label.outputs.branch_name }}"

          echo "Getting commits unique to $SOURCE_BRANCH..."
          COMMITS=$(git rev-list --reverse origin/$RELEASE_BRANCH..origin/$SOURCE_BRANCH)

          if [[ -z "$COMMITS" ]]; then
            echo "✅ No new commits to cherry-pick."
            exit 0
          fi

          echo -e "\n🧾 Commits to cherry-pick into $RELEASE_BRANCH:\n"
          printf "| %-10s | %-50s |\n" "SHA" "Message"
          printf "|%-12s|%-52s|\n" "------------" "----------------------------------------------------"

          for commit in $COMMITS; do
            git cherry-pick "$commit" || {
              echo "❌ Conflict while cherry-picking $commit. Aborting."
              exit 1
            }

            short_sha=$(git rev-parse --short $commit)
            message=$(git log --format=%s -n 1 $commit | cut -c1-50)
            printf "| %-10s | %-50s |\n" "$short_sha" "$message"
          done

          git push origin "$RELEASE_BRANCH"

      - name: Run CircleCI workflow
        if: steps.check_label.outputs.matched == 'true' && steps.check_label.outputs.branch_exists == 'true'
        run: |
          echo "🔥 Running CircleCI workflow"
